package exception;

public class Excepdemo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		System.out.println("Inside Main method..!!");
		Division.divide();
		NestedTryCatch.check();
	}

}
